apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-waf
  namespace: grupob3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-waf
  template:
    metadata:
      labels:
        app: apache-waf
    spec:
      containers:
        - name: apache
          ports:
             - containerPort: 80
          image: grupob3/pepsapachewaf:1.0

---
apiVersion: v1
kind: Service
metadata:
  name: apache-waf
  namespace: grupob3
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30703
  selector:
    app: apache-waf